### ISSUE TITLE
miniscript_string: Core accepts `+` sign for numbers

### ISSUE THREAD

**Issue by brunoerg** [brunoerg/bitcoinfuzz#34]
We got a crash on `miniscript_string` target due to validation of numbers. For `older()`, `after()`, `thresh()` and maybe other fragments, Bitcoin Core accept the usage of the `+` sign, e.g. (`l:older(+1)`, `u:after(+1)`), because of `ParseInt64` function. However, `rust-miniscript` checks the character itself, so it only accepts "1", "2", "3"..."9". 

```rs
if !('1'..='9').contains(&ch) {
    return Err(Error::Unexpected("Number must start with a digit 1-9".to_string()));
}
```

There is a test to ensure it doesn't accept those ones:
```rs
fn test_parse_num() {
    assert!(parse_num("0").is_ok());
    assert!(parse_num("00").is_err());
    assert!(parse_num("0000").is_err());
    assert!(parse_num("06").is_err());
    assert!(parse_num("+6").is_err());
    assert!(parse_num("-6").is_err());
}
```

**Comment by brunoerg** [comment]
@maflcko thanks. `ToIntegral` sounds better, I think we still would have some discrepancy because `ToIntegral` accepts, for example, 000001, while rust-miniscript would not, but it's ok

**Comment by brunoerg** [comment]
https://github.com/bitcoin/bitcoin/pull/30577

**Comment by apoelstra** [comment]
I wouldn't mind updating rust-miniscript. But we should probably update the Miniscript BIP with the exact number format.

**Comment by brunoerg** [comment]
Fixed https://github.com/bitcoin/bitcoin/pull/30577
