### ISSUE TITLE
psbt: extra data after PSBT

### ISSUE THREAD

**Issue by brunoerg** [brunoerg/bitcoinfuzz#43]
Just got a crash in psbt target, Bitcoin Core fails due to extra data after PSBT while rust-bitcoin seems not checking it.

Base64: cHNidP8BAAr///8AAAAAAAAAAD0Acw==

**Comment by brunoerg** [comment]
> Definitely from_str should have a max length check. Doesn't look like we have any from_slice type method but if we do then it should also do a check.

Should we open an issue in rust-bitcoin repo to facilitate tracking this?

**Comment by apoelstra** [comment]
Yes, please do!
