### ISSUE TITLE
Error when applying patches

### ISSUE THREAD

**Issue by brunoerg** [brunoerg/bitcoinfuzz#59]
```
bitcoinfuzz git:(main) ✗ git apply patches/*
error: No valid patches in input (allow with "--allow-empty")
```

**Comment by brunoerg** [comment]
cc: @hax0kartik

**Comment by hax0kartik** [comment]
Hi, could you check if the patches are already applied? I do not get any errors while applying either patch. Additionally, please check the output of the following commands `git apply patches/btcd_raw_network_message.patch -v` and `git apply patches/rust-bitcoin_raw_network_message.patch -v`

**Comment by brunoerg** [comment]
Yes, nevermind
