### ISSUE TITLE
[SoB] - de/serialization of Bitcoin protocol network messages 

### ISSUE THREAD

**Issue by brunoerg** [brunoerg/bitcoinfuzz#9]
`Bitcoinfuzz` is a project which applies differential fuzzing between Bitcoin projects. We started this project with miniscript support but we're expanding it. The proposal is to work on a fuzz target for de/serialization of Bitcoin protocol network messages. We intend to apply it with `Bitcoin Core`, `rust-bitcoin` and `btcd`.

The requirements are understanding/basic knowledge of:
- Bitcoin protocol
- Fuzzing
- Different programming languages (C++, Rust and Golang)
- Build systems

It's expected you to have a "security mindset". We can find interesting stuff with it and we need to be responsible :)

**Comment by zaidmstrr** [comment]
Hey, I was interested in the project can I send the review proposal for you?
